[package]
name = "varia-db"
version = "0.0.1-snapshot"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio =  { version = "1.35.1", features = ["full"] }
