name: Containerize

on:
    push:
      branches: [ "main" ]
      tags: [ 'v*.*.*' ]
    pull_request:
      branches: [ "main" ]
  
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner }}/varia-db

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          id-token: write
    
        steps:
          - uses: actions/checkout@v4.0.0
    
          - uses: docker/setup-buildx-action@v3.0.0
    
          - if: github.event_name != 'pull_request'
            uses: docker/login-action@v3.0.0
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
    
          - id: meta
            uses: docker/metadata-action@v5.0.0
            with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
          - id: build-and-push
            uses: docker/build-push-action@v5.0.0
            with:
              context: ./
              file: ./Dockerfile
              platforms: linux/amd64,linux/arm64
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
