name: Testing

on:
    push:
      branches: [ "*" ]
    pull_request:
      branches: [ "main" ]
  
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner }}/varia-db

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
    
        steps:
          - uses: actions/checkout@v4.0.0
    
          - uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              override: true

          - uses: actions-rs/cargo@v1
            with:
              command: test
